
name: ESLint CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         node-version: ['16.x']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ESLint
      run: npm i 
      run: node_modules/eslint/bin/eslint.js .